"""Markdown writer for `docs/measurements.md`."""

from __future__ import annotations

import re
from datetime import date
from typing import Any

from .plan import Result

_SECRETISH = re.compile(
    r"(eyJ[A-Za-z0-9_\-]{10,}\.[A-Za-z0-9_\-]+\.[A-Za-z0-9_\-]+|sk-[A-Za-z0-9_\-]{8,}|Bearer\s+\S+|[A-Za-z0-9_\-]{40,})"
)


def scrub(text: str) -> str:
    """Last line of defence: never let something token-shaped into the report."""
    return _SECRETISH.sub("[redacted]", text)


def _fmt(value: Any) -> str:
    if isinstance(value, (list, tuple)):
        return ", ".join(_fmt(v) for v in value) if value else "none"
    if value is None:
        return "none"
    return scrub(str(value))


def render_report(
    results: list[Result],
    *,
    provider: str,
    today: date,
    calls_used: int,
    max_calls: int,
    dry_run: bool = False,
) -> str:
    lines = ["# OpenDot measurements", ""]
    if dry_run:
        lines += [
            "> **DRY RUN: simulated data from a fake provider. These are not real measurements.**",
            "",
        ]
    lines += [
        f"- Provider: `{scrub(provider)}`",
        f"- Date: {today.isoformat()}",
        f"- Calls used: {calls_used} of {max_calls}",
        "- Generated by `opendot measure` (ARCHITECTURE.md section 8.5). Request content is never recorded.",
        "",
    ]
    for result in results:
        if result.warning:
            lines += [f"> **WARNING: {scrub(result.warning)}**", ""]
    lines += ["## Summary", "", "| # | Measurement | Result |", "|---|---|---|"]
    for index, result in enumerate(results, 1):
        lines.append(f"| {index} | {result.title} | {result.status} |")
    lines.append("")
    for index, result in enumerate(results, 1):
        lines += [f"## {index}. {result.title}", "", f"**Status: {result.status}**", ""]
        if result.summary:
            lines += [scrub(result.summary), ""]
        if result.evidence:
            lines += ["Evidence:", ""]
            lines += [f"- `{key}`: {_fmt(value)}" for key, value in result.evidence.items()]
            lines.append("")
    return "\n".join(lines).rstrip() + "\n"
